name: DevTools
path: src/chell_uoxou/devtools.php
main: DevTools\DevTools
version: 0.1.0
api: 1.6.4_Dev
load: STARTUP
author: chell_uoxou
description: Add some useful commands for PHPPO developers.
commands:
 makephar:
  permission: makephar.command
  usage: "makephar <Path|PluginName> / <system>"
 vardump:
  permission: vardump.command
  usage: "vardump <Variable Name> / <Variable Name> <Class Name>"
permissions:
 makephar.command:
  default: root
  description: "allow all command"
